#!/bin/sh
#

if [ `git rev-parse --abbrev-ref HEAD` != "release" ]; then
	exit 0
fi

echo 'Generating CHANGELOG.md file'

npx html-to-markdown ./src/assets/whatsnew/whatsnew.html --output="." && mv whatsnew.html.md CHANGELOG.md && git add CHANGELOG.md

# Check the return code
if [ $? -eq 1 ]; then
    # Error
	echo "Failed to generate CHANGELOG.md file"
	exit 1
else
	exit 0
fi