vars:
  VERSION:
    default: 1.0
  PACKAGE_NAME:
    default: com.eisos.proteusconnect
  DISPLAY_NAME:
    default: WE Bluetooth LE Terminal
  BUILD_NUMBER:
    default: 240813

platforms:
  ios:
    targets:
      App:
        bundleId: "com.we-online.ProteusConnect"
        version: $VERSION
        displayName: $DISPLAY_NAME
        buildNumber: $BUILD_NUMBER

  android:
    packageName: "com.eisos.android.terminal"
    versionName: $VERSION
    appName: $DISPLAY_NAME
    versionCode: $BUILD_NUMBER
